Comment GITHUB_TOKEN out

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -37,13 +37,13 @@ RUN pipx --version && poetry --version
 # Set the working directory in the container
 WORKDIR /workspace
 
-ARG GITHUB_TOKEN
-
-# Fail if GITHUB_TOKEN is not set
-RUN if [ -z "$GITHUB_TOKEN" ]; then echo "Error: GITHUB_TOKEN is not set" && exit 1; fi
-
-# Configure git to use the GITHUB_TOKEN
-RUN git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
+#ARG GITHUB_TOKEN
+#
+## Fail if GITHUB_TOKEN is not set
+#RUN if [ -z "$GITHUB_TOKEN" ]; then echo "Error: GITHUB_TOKEN is not set" && exit 1; fi
+#
+## Configure git to use the GITHUB_TOKEN
+#RUN git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
 
 # Install Taskmates
 ADD https://api.github.com/repos/taskmates/taskmates/git/refs/heads/main /tmp/taskmates-version.json
